# Generated by Django 3.1.3 on 2020-11-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201105_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop30',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pop30',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
