# Generated by Django 3.1.3 on 2020-11-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop30',
            name='spotify',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pop30',
            name='youtube',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('album', 'Album'), ('news', 'Noticia'), ('opinion', 'Opinion'), ('event', 'Evento'), ('song', 'Cancion')], max_length=255),
        ),
    ]
