# Generated by Django 3.1.3 on 2020-12-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201106_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='record_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='record_company',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('album', 'Album'), ('news', 'Noticia'), ('opinion', 'Articulo'), ('event', 'Evento'), ('song', 'Cancion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
